site_name: Docs Seg Dev

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  # - markdown.extensions.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  
nav:
  - Introdução: intro.md
  - Get started: get_start.md
  - Flutter tools: 
    - Iniciar um projeto Flutter: flutter_tools/init_project.md
    - Criar modulos: flutter_tools/criar_modulo.md
  - Extension Develop: 
    - Introdução: ext_dev/intro.md
    - Gerar templates: ext_dev/gerar_templates.md

theme:
  name: null
  custom_dir: mkdocs-material/material

  palette:
    primary: white

  # features:
  #   - navigation.expand

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo